import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "./components/layout/Topbar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ServiceAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Providers>
          <div className="app-layout">
            <aside className="sidebar">Sidebar</aside>
            <div className="content">
              <Topbar />
              <main className="main-content">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
