"""Ensure integration_logs id uses identity and sequence is aligned."""

from alembic import op

# revision identifiers, used by Alembic.
revision = "20241205_02"
down_revision = "20241205_01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        DECLARE
            next_id BIGINT;
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'integration_logs'
                  AND column_name = 'id'
            ) THEN

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'integration_logs'
                      AND column_name = 'id'
                      AND identity_generation IS NOT NULL
                ) THEN
                    EXECUTE 'ALTER TABLE integration_logs ALTER COLUMN id DROP DEFAULT';
                    EXECUTE 'ALTER TABLE integration_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
                END IF;

                -- Выровнять sequence: start = max(id)+1
                EXECUTE 'SELECT COALESCE(MAX(id), 0) + 1 FROM integration_logs' INTO next_id;
                EXECUTE format('ALTER TABLE integration_logs ALTER COLUMN id RESTART WITH %s', next_id);

            END IF;
        END$$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'integration_logs'
                  AND column_name = 'id'
                  AND identity_generation IS NOT NULL
            ) THEN
                EXECUTE 'ALTER TABLE integration_logs ALTER COLUMN id DROP IDENTITY IF EXISTS';
            END IF;
        END$$;
        """
    )
