"""Ensure integration_logs id uses identity."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20241205_02"
down_revision = "20241205_01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'integration_logs'
                  AND column_name = 'id'
                  AND identity_generation IS NOT NULL
            ) THEN
                EXECUTE 'ALTER TABLE integration_logs ALTER COLUMN id DROP DEFAULT';
                EXECUTE 'ALTER TABLE integration_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;
        END$$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'integration_logs'
                  AND column_name = 'id'
                  AND identity_generation IS NOT NULL
            ) THEN
                EXECUTE 'ALTER TABLE integration_logs ALTER COLUMN id DROP IDENTITY IF EXISTS';
            END IF;
        END$$;
        """
    )
